import { createContext, useContext, useState, type ReactNode } from "react";

export type Language = "en" | "hi";

interface LanguageContextType {
  lang: Language;
  setLang: (l: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  lang: "en",
  setLang: () => {},
  t: (k) => k,
});

export const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navbar
    "nav.brand": "🍽️ Sync Restaurant",
    "nav.settings": "Settings",
    "nav.changePassword": "Change Password",
    "nav.updateCredentials": "Update your credentials",
    "nav.signOut": "Sign Out",
    "nav.signOutMsg": "You'll need to log in again to access the dashboard.",
    "nav.active": "Active",
    // Auth
    "auth.login": "Login to Continue",
    "auth.createAccount": "Create Account",
    "auth.signIn": "SIGN IN",
    "auth.signUp": "SIGN UP",
    "auth.newUser": "New User?",
    "auth.haveAccount": "Already have account?",
    "auth.rememberMe": "Remember Me",
    "auth.fullName": "Full Name",
    "auth.emailOrContact": "Email or Contact Number",
    "auth.contactNumber": "Contact Number (10 digits)",
    "auth.password": "Password",
    "auth.confirmPassword": "Confirm Password",
    // Settings
    "settings.title": "Settings",
    "settings.restaurantInfo": "Restaurant Info",
    "settings.tax": "Tax / GST",
    "settings.hours": "Operating Hours",
    "settings.tables": "Table Management",
    "settings.language": "Language",
    "settings.saveChanges": "Save Changes",
    "settings.restaurantSubtitle": "Basic details about your restaurant",
    "settings.taxSubtitle": "Configure applicable taxes on bills",
    "settings.hoursSubtitle": "Set your restaurant's open and close times",
    "settings.tablesSubtitle": "Add, edit, or remove dining tables",
    "settings.languageSubtitle": "Choose your preferred language",
    "settings.restaurantName": "Restaurant Name",
    "settings.email": "Email Address",
    "settings.phone": "Phone Number",
    "settings.website": "Website",
    "settings.address": "Full Address",
    "settings.gst": "GST Number",
    "settings.fssai": "FSSAI License",
    "settings.addTax": "Add Tax / Charge",
    "settings.closed": "Closed",
    "settings.active": "Active",
    "settings.inactive": "Inactive",
    "settings.addTable": "Add New Table",
    "settings.newTable": "New Table",
    "settings.tableNumber": "Table number (e.g. T7)",
    "settings.seats": "Seats",
    "settings.cancel": "Cancel",
    "settings.sections": "Sections",
    // Dashboard
    "dash.morning": "Good Morning",
    "dash.afternoon": "Good Afternoon",
    "dash.evening": "Good Evening",
    "dash.title": "Restaurant Dashboard",
    "dash.subtitle": "Manage your restaurant efficiently",
    "dash.billing": "Billing",
    "dash.billingDesc": "Manage orders easily",
    "dash.menu": "Menu",
    "dash.menuDesc": "Update food items",
    "dash.inventory": "Inventory",
    "dash.inventoryDesc": "Track stock",
    "dash.reports": "Reports",
    "dash.reportsDesc": "View analytics",
    "dash.clickManage": "Click to manage →",
    // Inventory
    "inv.title": "Inventory",
    "inv.dashboard": "Dashboard",
    "inv.log": "Today's Log",
    "inv.items": "Items",
    "inv.totalItems": "Total Items",
    "inv.lowStock": "Low Stock",
    "inv.stockToday": "Stocked Today",
    "inv.usedToday": "Used Today",
    "inv.currentStock": "Current Stock",
    "inv.search": "Search items...",
    "inv.stockIn": "Stock In",
    "inv.markUsed": "Mark Used",
    "inv.addItem": "+ Add Item",
    "inv.loading": "Loading inventory...",
    "inv.noItems": "No items match",
    "inv.noTransactions": "No transactions yet today.",
    "inv.useStockIn": "Use \"Stock In\" or \"Mark Used\" to log activity.",
    "inv.todayTransactions": "Today's Transactions",
    "inv.allItems": "All Items & Triggers",
    "inv.lowStockAlert": "Low Stock Alert",
    "inv.runningLow": "is running low!",
    "inv.remaining": "remaining",
    "inv.min": "min",
    "inv.restock": "Please restock soon.",
    "inv.networkError": "Network error. Please try again.",
    "inv.retry": "Retry",
    "inv.selectItem": "Please select an item.",
    "inv.validQty": "Enter a valid quantity.",
    "inv.available": "available",
    "inv.addToStock": "Add to Stock",
    "inv.deductStock": "Deduct from Stock",
    "inv.itemName": "Item Name",
    "inv.unit": "Unit",
    "inv.openingStock": "Opening Stock",
    "inv.minQty": "Min Qty Trigger",
    "inv.minQtyHint": "Alert fires when stock drops to this level.",
    "inv.newItem": "New Item",
    "inv.item": "Item",
    "inv.quantity": "Quantity",
    "inv.currentStockCol": "Current Stock",
    "inv.minTrigger": "Min Trigger",
    "inv.status": "Status",
    // Menu
    "menu.title": "Menu Manager",
    "menu.totalItems": "Total Items",
    "menu.veg": "Veg",
    "menu.nonVeg": "Non-Veg",
    "menu.search": "Search menu items...",
    "menu.all": "All",
    "menu.addNew": "+ Add New Item",
    "menu.noItems": "No items found.",
    "menu.itemName": "Item Name",
    "menu.price": "Price (₹)",
    "menu.category": "Category",
    "menu.edit": "Edit",
    "menu.delete": "Delete",
    "menu.editItem": "Edit Item",
    "menu.addItem": "Add New Item",
    "menu.cancel": "Cancel",
    "menu.saveChanges": "Save Changes",
    "menu.itemPlaceholder": "e.g. Paneer Tikka",
    "menu.pricePlaceholder": "e.g. 250",

     // Billing / POS
    "bill.table": "Table",
    "bill.captain": "Captain",
    "bill.search": "Search by Code/Barcode/Name",
    "bill.itemName": "Item Name",
    "bill.qtyPrice": "Qty · Price",
    "bill.total": "Total",
    "bill.noOrder": "No order · Search and add items",
    "bill.subtotal": "Subtotal",
    "bill.discount": "Discount",
    "bill.gst": "GST (5%)",
    "bill.items": "ITEMS",
    "bill.printKot": "Print KOT",
    "bill.saveBill": "Save Bill",
    "bill.printBill": "Print Bill",
    "bill.saveKot": "Save KOT",
    "bill.settleBill": "Settle Bill",
    "bill.lastBill": "Last Bill",
    "bill.loading": "Loading...",
    "bill.addTable": "Add New Table",
    "bill.tableName": "Table name",
    "bill.cancel": "Cancel",
    "bill.add": "Add",
    "bill.adding": "Adding...",
    "bill.hall": "Hall",
    "bill.family": "Family",
    "bill.parcel": "Parcel",
    "bill.noTables": "No tables in this zone",
    "bill.free": "Free",
    // Reports - Sidebar
    "rep.title": "Reports",
    "rep.todayReport": "Today's Report",
    "rep.topProducts": "Top Products",
    "rep.customization": "Customization",
    "rep.monthlyReport": "Monthly Report",
    "rep.back": "← Back",
    // Reports - Daily
    "rep.daily.title": "Today Report",
    "rep.daily.export": "Export",
    "rep.daily.totalSales": "Total Sales",
    "rep.daily.discount": "Discount",
    "rep.daily.orders": "Orders",
    "rep.daily.netSales": "Net Sales",
    "rep.daily.avgOrder": "Avg Order",
    "rep.daily.revenueByProduct": "Revenue by Product",
    "rep.daily.topProducts": "Top Selling Products",
    "rep.daily.today": "Today",
    "rep.daily.product": "Product",
    "rep.daily.qty": "Qty",
    "rep.daily.revenue": "Revenue",
    "rep.daily.noOrders": "No orders today",
    "rep.daily.loading": "Loading...",
    "rep.daily.error": "Failed to load report.",
    // Reports - Monthly
    "rep.monthly.title": "Monthly Report",
    "rep.monthly.totalSales": "Total Sales",
    "rep.monthly.discount": "Discount",
    "rep.monthly.refund": "Refund",
    "rep.monthly.netSales": "Net Sales",
    "rep.monthly.orders": "Orders",
    "rep.monthly.avgOrder": "Avg Order",
    "rep.monthly.topProducts": "Top Products",
    "rep.monthly.paymentMethods": "Payment Methods",
    "rep.monthly.noDataMonth": "No data this month",
    "rep.monthly.noPaymentData": "No payment data",
    "rep.monthly.download": "📄 Download Report",
    "rep.monthly.error": "Failed to load report.",
    // Reports - Top Products
    "rep.top.title": "Top Products",
    "rep.top.export": "Export",
    "rep.top.totalItems": "Total Items Sold",
    "rep.top.totalRevenue": "Total Revenue",
    "rep.top.topProduct": "Top Product",
    "rep.top.search": "Search product...",
    "rep.top.topSelling": "Top Selling",
    "rep.top.lowSelling": "Low Selling",
    "rep.top.reset": "Reset",
    "rep.top.noOrders": "No orders yet ❌",
    "rep.top.noProducts": "No products found ❌",
    "rep.top.salesChart": "Sales Chart",
    "rep.top.product": "Product",
    "rep.top.qty": "Qty",
    "rep.top.revenue": "Revenue",
    "rep.top.error": "Failed to load products.",
    // Reports - Customization
    "rep.custom.title": "Custom Report",
    "rep.custom.subtitle": "Filter and generate your own report",
    "rep.custom.allPayments": "All Payments",
    "rep.custom.cash": "Cash",
    "rep.custom.upi": "UPI",
    "rep.custom.card": "Card",
    "rep.custom.online": "Online",
    "rep.custom.allOrders": "All Orders",
    "rep.custom.dineIn": "Dine-in",
    "rep.custom.takeaway": "Takeaway",
    "rep.custom.generate": "Generate",
    "rep.custom.loading": "Loading...",
    "rep.custom.reset": "Reset",
    "rep.custom.download": "📄 Download Report",
    "rep.custom.noData": "No data found ❌",
    "rep.custom.totalSales": "Total Sales",
    "rep.custom.itemsSold": "Items Sold",
    "rep.custom.topProduct": "Top Product",
    "rep.custom.salesChart": "Sales Chart",
    "rep.custom.item": "Item",
    "rep.custom.qty": "Qty",
    "rep.custom.revenue": "Revenue",
    "rep.custom.payment": "Payment",
    "rep.custom.type": "Type",
    "rep.custom.error": "Failed to load report.",
  },

  hi: {
    // Navbar
    "nav.brand": "🍽️ सिंक रेस्टोरेंट",
    "nav.settings": "सेटिंग्स",
    "nav.changePassword": "पासवर्ड बदलें",
    "nav.updateCredentials": "अपनी जानकारी अपडेट करें",
    "nav.signOut": "साइन आउट",
    "nav.signOutMsg": "डैशबोर्ड एक्सेस करने के लिए फिर से लॉगिन करना होगा।",
    "nav.active": "सक्रिय",
    // Auth
    "auth.login": "लॉगिन करें",
    "auth.createAccount": "अकाउंट बनाएं",
    "auth.signIn": "साइन इन",
    "auth.signUp": "साइन अप",
    "auth.newUser": "नए यूजर?",
    "auth.haveAccount": "पहले से अकाउंट है?",
    "auth.rememberMe": "मुझे याद रखें",
    "auth.fullName": "पूरा नाम",
    "auth.emailOrContact": "ईमेल या मोबाइल नंबर",
    "auth.contactNumber": "मोबाइल नंबर (10 अंक)",
    "auth.password": "पासवर्ड",
    "auth.confirmPassword": "पासवर्ड की पुष्टि करें",
    // Settings
    "settings.title": "सेटिंग्स",
    "settings.restaurantInfo": "रेस्टोरेंट जानकारी",
    "settings.tax": "टैक्स / GST",
    "settings.hours": "काम के घंटे",
    "settings.tables": "टेबल प्रबंधन",
    "settings.language": "भाषा",
    "settings.saveChanges": "बदलाव सहेजें",
    "settings.restaurantSubtitle": "आपके रेस्टोरेंट की बुनियादी जानकारी",
    "settings.taxSubtitle": "बिल पर लागू टैक्स कॉन्फिगर करें",
    "settings.hoursSubtitle": "रेस्टोरेंट के खुलने/बंद होने का समय सेट करें",
    "settings.tablesSubtitle": "टेबल जोड़ें, संपादित करें या हटाएं",
    "settings.languageSubtitle": "अपनी पसंदीदा भाषा चुनें",
    "settings.restaurantName": "रेस्टोरेंट का नाम",
    "settings.email": "ईमेल पता",
    "settings.phone": "फोन नंबर",
    "settings.website": "वेबसाइट",
    "settings.address": "पूरा पता",
    "settings.gst": "GST नंबर",
    "settings.fssai": "FSSAI लाइसेंस",
    "settings.addTax": "टैक्स / शुल्क जोड़ें",
    "settings.closed": "बंद",
    "settings.active": "सक्रिय",
    "settings.inactive": "निष्क्रिय",
    "settings.addTable": "नई टेबल जोड़ें",
    "settings.newTable": "नई टेबल",
    "settings.tableNumber": "टेबल नंबर (जैसे T7)",
    "settings.seats": "सीटें",
    "settings.cancel": "रद्द करें",
    "settings.sections": "अनुभाग",
    // Dashboard
    "dash.morning": "सुप्रभात",
    "dash.afternoon": "नमस्कार",
    "dash.evening": "शुभ संध्या",
    "dash.title": "रेस्टोरेंट डैशबोर्ड",
    "dash.subtitle": "अपने रेस्टोरेंट को कुशलता से प्रबंधित करें",
    "dash.billing": "बिलिंग",
    "dash.billingDesc": "ऑर्डर आसानी से प्रबंधित करें",
    "dash.menu": "मेनू",
    "dash.menuDesc": "खाद्य पदार्थ अपडेट करें",
    "dash.inventory": "इन्वेंटरी",
    "dash.inventoryDesc": "स्टॉक ट्रैक करें",
    "dash.reports": "रिपोर्ट",
    "dash.reportsDesc": "विश्लेषण देखें",
    "dash.clickManage": "प्रबंधित करने के लिए क्लिक करें →",
    // Inventory
    "inv.title": "इन्वेंटरी",
    "inv.dashboard": "डैशबोर्ड",
    "inv.log": "आज का लॉग",
    "inv.items": "आइटम",
    "inv.totalItems": "कुल आइटम",
    "inv.lowStock": "कम स्टॉक",
    "inv.stockToday": "आज स्टॉक किया",
    "inv.usedToday": "आज उपयोग किया",
    "inv.currentStock": "वर्तमान स्टॉक",
    "inv.search": "आइटम खोजें...",
    "inv.stockIn": "स्टॉक इन",
    "inv.markUsed": "उपयोग किया",
    "inv.addItem": "+ आइटम जोड़ें",
    "inv.loading": "इन्वेंटरी लोड हो रही है...",
    "inv.noItems": "कोई आइटम नहीं मिला",
    "inv.noTransactions": "आज कोई लेनदेन नहीं हुआ।",
    "inv.useStockIn": "गतिविधि लॉग करने के लिए \"स्टॉक इन\" या \"उपयोग किया\" का उपयोग करें।",
    "inv.todayTransactions": "आज के लेनदेन",
    "inv.allItems": "सभी आइटम और ट्रिगर",
    "inv.lowStockAlert": "कम स्टॉक अलर्ट",
    "inv.runningLow": "का स्टॉक कम हो रहा है!",
    "inv.remaining": "बचा है",
    "inv.min": "न्यूनतम",
    "inv.restock": "कृपया जल्द स्टॉक भरें।",
    "inv.networkError": "नेटवर्क त्रुटि। कृपया पुनः प्रयास करें।",
    "inv.retry": "पुनः प्रयास",
    "inv.selectItem": "कृपया एक आइटम चुनें।",
    "inv.validQty": "वैध मात्रा दर्ज करें।",
    "inv.available": "उपलब्ध",
    "inv.addToStock": "स्टॉक में जोड़ें",
    "inv.deductStock": "स्टॉक से घटाएं",
    "inv.itemName": "आइटम का नाम",
    "inv.unit": "इकाई",
    "inv.openingStock": "प्रारंभिक स्टॉक",
    "inv.minQty": "न्यूनतम मात्रा ट्रिगर",
    "inv.minQtyHint": "स्टॉक इस स्तर तक गिरने पर अलर्ट मिलेगा।",
    "inv.newItem": "नया आइटम",
    "inv.item": "आइटम",
    "inv.quantity": "मात्रा",
    "inv.currentStockCol": "वर्तमान स्टॉक",
    "inv.minTrigger": "न्यूनतम ट्रिगर",
    "inv.status": "स्थिति",
    // Menu
    "menu.title": "मेनू प्रबंधक",
    "menu.totalItems": "कुल आइटम",
    "menu.veg": "शाकाहारी",
    "menu.nonVeg": "मांसाहारी",
    "menu.search": "मेनू आइटम खोजें...",
    "menu.all": "सभी",
    "menu.addNew": "+ नया आइटम जोड़ें",
    "menu.noItems": "कोई आइटम नहीं मिला।",
    "menu.itemName": "आइटम का नाम",
    "menu.price": "कीमत (₹)",
    "menu.category": "श्रेणी",
    "menu.edit": "संपादित करें",
    "menu.delete": "हटाएं",
    "menu.editItem": "आइटम संपादित करें",
    "menu.addItem": "नया आइटम जोड़ें",
    "menu.cancel": "रद्द करें",
    "menu.saveChanges": "बदलाव सहेजें",
    "menu.itemPlaceholder": "जैसे पनीर टिक्का",
    "menu.pricePlaceholder": "जैसे 250",
     // Billing / POS
    "bill.table": "टेबल",
    "bill.captain": "कैप्टन",
    "bill.search": "कोड/बारकोड/नाम से खोजें",
    "bill.itemName": "आइटम नाम",
    "bill.qtyPrice": "मात्रा · कीमत",
    "bill.total": "कुल",
    "bill.noOrder": "कोई ऑर्डर नहीं · आइटम खोजें और जोड़ें",
    "bill.subtotal": "उप-योग",
    "bill.discount": "छूट",
    "bill.gst": "GST (5%)",
    "bill.items": "आइटम",
    "bill.printKot": "KOT प्रिंट",
    "bill.saveBill": "बिल सेव करें",
    "bill.printBill": "बिल प्रिंट",
    "bill.saveKot": "KOT सेव करें",
    "bill.settleBill": "बिल सेटल करें",
    "bill.lastBill": "पिछला बिल",
    "bill.loading": "लोड हो रहा है...",
    "bill.addTable": "नई टेबल जोड़ें",
    "bill.tableName": "टेबल नाम",
    "bill.cancel": "रद्द करें",
    "bill.add": "जोड़ें",
    "bill.adding": "जोड़ रहा है...",
    "bill.hall": "हॉल",
    "bill.family": "फैमिली",
    "bill.parcel": "पार्सल",
    "bill.noTables": "इस ज़ोन में कोई टेबल नहीं",
    "bill.free": "खाली",
    // Reports - Sidebar
    "rep.title": "रिपोर्ट",
    "rep.todayReport": "आज की रिपोर्ट",
    "rep.topProducts": "टॉप उत्पाद",
    "rep.customization": "कस्टमाइज़ेशन",
    "rep.monthlyReport": "मासिक रिपोर्ट",
    "rep.back": "← वापस",
    // Reports - Daily
    "rep.daily.title": "आज की रिपोर्ट",
    "rep.daily.export": "निर्यात करें",
    "rep.daily.totalSales": "कुल बिक्री",
    "rep.daily.discount": "छूट",
    "rep.daily.orders": "ऑर्डर",
    "rep.daily.netSales": "शुद्ध बिक्री",
    "rep.daily.avgOrder": "औसत ऑर्डर",
    "rep.daily.revenueByProduct": "उत्पाद के अनुसार राजस्व",
    "rep.daily.topProducts": "सबसे ज़्यादा बिकने वाले उत्पाद",
    "rep.daily.today": "आज",
    "rep.daily.product": "उत्पाद",
    "rep.daily.qty": "मात्रा",
    "rep.daily.revenue": "राजस्व",
    "rep.daily.noOrders": "आज कोई ऑर्डर नहीं",
    "rep.daily.loading": "लोड हो रहा है...",
    "rep.daily.error": "रिपोर्ट लोड करने में विफल।",
    // Reports - Monthly
    "rep.monthly.title": "मासिक रिपोर्ट",
    "rep.monthly.totalSales": "कुल बिक्री",
    "rep.monthly.discount": "छूट",
    "rep.monthly.refund": "वापसी",
    "rep.monthly.netSales": "शुद्ध बिक्री",
    "rep.monthly.orders": "ऑर्डर",
    "rep.monthly.avgOrder": "औसत ऑर्डर",
    "rep.monthly.topProducts": "टॉप उत्पाद",
    "rep.monthly.paymentMethods": "भुगतान विधियाँ",
    "rep.monthly.noDataMonth": "इस महीने कोई डेटा नहीं",
    "rep.monthly.noPaymentData": "कोई भुगतान डेटा नहीं",
    "rep.monthly.download": "📄 रिपोर्ट डाउनलोड करें",
    "rep.monthly.error": "रिपोर्ट लोड करने में विफल।",
    // Reports - Top Products
    "rep.top.title": "टॉप उत्पाद",
    "rep.top.export": "निर्यात करें",
    "rep.top.totalItems": "कुल बिके आइटम",
    "rep.top.totalRevenue": "कुल राजस्व",
    "rep.top.topProduct": "टॉप उत्पाद",
    "rep.top.search": "उत्पाद खोजें...",
    "rep.top.topSelling": "सबसे ज़्यादा बिकने वाले",
    "rep.top.lowSelling": "कम बिकने वाले",
    "rep.top.reset": "रीसेट",
    "rep.top.noOrders": "अभी कोई ऑर्डर नहीं ❌",
    "rep.top.noProducts": "कोई उत्पाद नहीं मिला ❌",
    "rep.top.salesChart": "बिक्री चार्ट",
    "rep.top.product": "उत्पाद",
    "rep.top.qty": "मात्रा",
    "rep.top.revenue": "राजस्व",
    "rep.top.error": "उत्पाद लोड करने में विफल।",
    // Reports - Customization
    "rep.custom.title": "कस्टम रिपोर्ट",
    "rep.custom.subtitle": "फ़िल्टर करें और अपनी रिपोर्ट बनाएं",
    "rep.custom.allPayments": "सभी भुगतान",
    "rep.custom.cash": "नकद",
    "rep.custom.upi": "UPI",
    "rep.custom.card": "कार्ड",
    "rep.custom.online": "ऑनलाइन",
    "rep.custom.allOrders": "सभी ऑर्डर",
    "rep.custom.dineIn": "डाइन-इन",
    "rep.custom.takeaway": "टेकअवे",
    "rep.custom.generate": "जेनरेट करें",
    "rep.custom.loading": "लोड हो रहा है...",
    "rep.custom.reset": "रीसेट",
    "rep.custom.download": "📄 रिपोर्ट डाउनलोड करें",
    "rep.custom.noData": "कोई डेटा नहीं मिला ❌",
    "rep.custom.totalSales": "कुल बिक्री",
    "rep.custom.itemsSold": "बेचे गए आइटम",
    "rep.custom.topProduct": "टॉप उत्पाद",
    "rep.custom.salesChart": "बिक्री चार्ट",
    "rep.custom.item": "आइटम",
    "rep.custom.qty": "मात्रा",
    "rep.custom.revenue": "राजस्व",
    "rep.custom.payment": "भुगतान",
    "rep.custom.type": "प्रकार",
    "rep.custom.error": "रिपोर्ट लोड करने में विफल।",
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Language>(() => {
    return (localStorage.getItem("appLang") as Language) || "en";
  });

  const setLang = (l: Language) => {
    setLangState(l);
    localStorage.setItem("appLang", l);
  };

  const t = (key: string): string => {
    return translations[lang][key] || translations["en"][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLang = () => useContext(LanguageContext);